//! V8.0 S2 — Buchberger's algorithm for the Gröbner basis of a multivariate
//! polynomial ideal, plus the normal-form reduction it depends on.
//!
//! Operates on [`MPoly`] from `mpoly.rs`. The reduced Gröbner basis returned
//! is canonical for the chosen monomial order: same ideal, same input order
//! → same basis.

use std::collections::VecDeque;

use num::One;

use crate::mpoly::{MCoeff, MPoly, Monomial};

/// Iteration safety cap. Buchberger always terminates by Dickson's lemma, but
/// pathological inputs can produce huge intermediate bases; surfacing a
/// "best-effort so far" beats spinning.
pub const MAX_BUCHBERGER_STEPS: usize = 50_000;

// ---------- S-polynomial ----------------------------------------------------

/// `S(f, g) = (lcm/lt(f))·f − (lcm/lt(g))·g`, where `lcm = lcm(lm f, lm g)`.
pub fn s_polynomial(f: &MPoly, g: &MPoly) -> MPoly {
    let lm_f = f.lm().expect("S-polynomial of zero polynomial");
    let lc_f = f.lc().expect("S-polynomial of zero polynomial");
    let lm_g = g.lm().expect("S-polynomial of zero polynomial");
    let lc_g = g.lc().expect("S-polynomial of zero polynomial");

    let lcm = lm_f.lcm(lm_g);
    let m_f = Monomial::div(&lcm, lm_f).expect("lm_f divides lcm by construction");
    let m_g = Monomial::div(&lcm, lm_g).expect("lm_g divides lcm by construction");

    let inv_lc_f = MCoeff::one() / lc_f;
    let inv_lc_g = MCoeff::one() / lc_g;

    let term_f = f.monomial_mul(&inv_lc_f, &m_f);
    let term_g = g.monomial_mul(&inv_lc_g, &m_g);
    term_f.sub(&term_g)
}

// ---------- Normal-form reduction ------------------------------------------

/// Reduce `p` modulo `basis`: at each step, if some basis polynomial's
/// leading monomial divides the current leading monomial of `p`, subtract a
/// monomial multiple of that polynomial that cancels the leading term;
/// otherwise move that leading term to the remainder and continue with the
/// rest of `p`. Returns the remainder, in canonical form under `p.order`.
pub fn normal_form(p: &MPoly, basis: &[MPoly]) -> MPoly {
    let vars = p.vars.clone();
    let order = p.order;
    let mut p = p.clone();
    let mut r = MPoly::zero(vars.clone(), order);

    while !p.is_zero() {
        let lm_p = p.lm().unwrap().clone();
        let lc_p = p.lc().unwrap().clone();

        // Find a basis polynomial whose leading monomial divides p's.
        let mut reduced_this_iter = false;
        for h in basis {
            if h.is_zero() { continue; }
            let lm_h = h.lm().unwrap();
            if lm_h.divides(&lm_p) {
                let m = Monomial::div(&lm_p, lm_h).expect("just checked divides");
                let c = &lc_p / h.lc().unwrap();
                let to_sub = h.monomial_mul(&c, &m);
                p = p.sub(&to_sub);
                reduced_this_iter = true;
                break;
            }
        }

        if !reduced_this_iter {
            // Move the leading term of p into r, drop it from p.
            let mut single = MPoly::zero(vars.clone(), order);
            single.terms.push((lm_p, lc_p));
            r = r.add(&single);
            // p still has the same leading term; remove it.
            p.terms.remove(0);
        }
    }
    r
}

// ---------- Buchberger ------------------------------------------------------

fn coprime(a: &Monomial, b: &Monomial) -> bool {
    a.0.iter().zip(b.0.iter()).all(|(x, y)| *x == 0 || *y == 0)
}

/// Compute a Gröbner basis of the ideal generated by `input` under the order
/// each polynomial carries. All inputs must share `vars` and `order`. The
/// result is then minimised + fully reduced before return: leading
/// coefficients are 1, no element's leading monomial is redundant, and each
/// element is in normal form modulo the others — i.e. the *reduced* Gröbner
/// basis, which is canonical for the ideal under the chosen order.
pub fn buchberger(input: &[MPoly]) -> Vec<MPoly> {
    let nonzero: Vec<MPoly> = input.iter().filter(|p| !p.is_zero()).cloned().collect();
    if nonzero.is_empty() { return vec![]; }
    let vars = nonzero[0].vars.clone();
    let order = nonzero[0].order;
    for p in &nonzero {
        assert_eq!(p.vars, vars, "buchberger: variable mismatch");
        assert_eq!(p.order, order, "buchberger: order mismatch");
    }

    let mut g: Vec<MPoly> = nonzero;
    let mut pairs: VecDeque<(usize, usize)> = VecDeque::new();
    for i in 0..g.len() {
        for j in i + 1..g.len() {
            pairs.push_back((i, j));
        }
    }

    let mut steps = 0;
    while let Some((i, j)) = pairs.pop_front() {
        if steps >= MAX_BUCHBERGER_STEPS { break; }
        steps += 1;

        // Buchberger's first criterion: coprime leading monomials make
        // S(f, g) reduce to zero, so we can skip the pair without computing.
        let lm_i = g[i].lm().expect("non-zero by construction").clone();
        let lm_j = g[j].lm().expect("non-zero by construction").clone();
        if coprime(&lm_i, &lm_j) { continue; }

        let s = s_polynomial(&g[i], &g[j]);
        let r = normal_form(&s, &g);
        if !r.is_zero() {
            let new_idx = g.len();
            for k in 0..new_idx {
                pairs.push_back((k, new_idx));
            }
            g.push(r);
        }
    }

    reduce_basis(g)
}

/// Convert a Gröbner basis to its minimal + reduced form.
fn reduce_basis(mut g: Vec<MPoly>) -> Vec<MPoly> {
    // 1. Normalise leading coefficients to 1.
    for p in &mut g {
        if let Some(lc) = p.lc().cloned() {
            if !lc.is_one() {
                let inv = MCoeff::one() / lc;
                *p = p.scalar_mul(&inv);
            }
        }
    }

    // 2. Minimise: drop any g_i whose lm is divisible by another g_j's lm.
    let mut keep = vec![true; g.len()];
    for i in 0..g.len() {
        if !keep[i] { continue; }
        let lm_i = g[i].lm().unwrap().clone();
        for j in 0..g.len() {
            if i == j || !keep[j] { continue; }
            let lm_j = g[j].lm().unwrap();
            if lm_j.divides(&lm_i) && lm_j != &lm_i {
                keep[i] = false;
                break;
            }
            // If both LMs are equal, keep the lower-indexed one
            // (deterministic; either generates the same ideal).
            if lm_j == &lm_i && j < i {
                keep[i] = false;
                break;
            }
        }
    }
    let mut g: Vec<MPoly> = g.into_iter().zip(keep).filter(|(_, k)| *k).map(|(p, _)| p).collect();

    // 3. Reduce each element modulo the others (full reduction).
    let mut i = 0;
    while i < g.len() {
        let others: Vec<MPoly> = g.iter().enumerate()
            .filter(|(j, _)| *j != i)
            .map(|(_, p)| p.clone())
            .collect();
        let reduced = normal_form(&g[i], &others);
        if reduced.is_zero() {
            // Should not happen for a minimal basis, but defensively drop it.
            g.remove(i);
        } else {
            // Renormalise leading coefficient.
            let lc = reduced.lc().unwrap().clone();
            let normalised = if lc.is_one() {
                reduced
            } else {
                let inv = MCoeff::one() / lc;
                reduced.scalar_mul(&inv)
            };
            g[i] = normalised;
            i += 1;
        }
    }

    // 4. Sort the final basis by descending leading monomial for a canonical
    //    output order.
    let order = if let Some(p) = g.first() { p.order } else { return g };
    g.sort_by(|a, b| order.cmp(b.lm().unwrap(), a.lm().unwrap()));
    g
}

// ---------- Tests -----------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mpoly::{expr_to_mpoly, MonomialOrder};
    use maxima_core::intern;

    fn vars2() -> Vec<maxima_core::SymbolId> {
        vec![intern("x"), intern("y")]
    }

    fn parse(s: &str, vars: &[maxima_core::SymbolId], order: MonomialOrder) -> MPoly {
        let e = maxima_parser::parse(s);
        expr_to_mpoly(&e, vars, order).expect("polynomial parse")
    }

    // ---- S-polynomial sanity ----

    #[test] fn s_polynomial_cancels_leading() {
        let v = vars2();
        let ord = MonomialOrder::Grlex;
        let f = parse("x^2*y - 1", &v, ord);
        let g = parse("x*y^2 - x", &v, ord);
        let s = s_polynomial(&f, &g);
        // The leading terms of (lcm/lt_f)*f and (lcm/lt_g)*g cancel, so the
        // leading monomial of s must be strictly smaller than lcm.
        let lcm = f.lm().unwrap().lcm(g.lm().unwrap());
        if let Some(lm_s) = s.lm() {
            assert_ne!(*lm_s, lcm, "S-polynomial leading must drop below lcm");
        }
    }

    // ---- Normal-form reduction ----

    #[test] fn normal_form_zero_when_divisible() {
        let v = vars2();
        let ord = MonomialOrder::Grlex;
        let f = parse("x^2 + 2*x + 1", &v, ord);
        let one_basis = vec![parse("x + 1", &v, ord)];
        let r = normal_form(&f, &one_basis);
        // x^2 + 2x + 1 = (x + 1)^2, so reducing by x + 1 leaves 0.
        assert!(r.is_zero(), "remainder = {:?}", r.terms);
    }

    #[test] fn normal_form_keeps_unreducible_terms() {
        let v = vars2();
        let ord = MonomialOrder::Grlex;
        // y^2 isn't divisible by x + 1, so it survives the reduction.
        let f = parse("x^2*y + y^2", &v, ord);
        let basis = vec![parse("x", &v, ord)];
        let r = normal_form(&f, &basis);
        // x is a basis lm; it divides x^2 y → remove x^2 y. y^2 survives.
        assert_eq!(r.terms.len(), 1);
        assert_eq!(r.terms[0].0.0, vec![0, 2]);
    }

    // ---- Buchberger on textbook examples ----

    #[test] fn groebner_of_intersection_unit_circle_with_y_eq_x_squared() {
        // {x^2 + y^2 - 1, x - y^2}: intersection of unit circle and y = x^2.
        // Under lex with vars=[x, y], the reduced basis is well-known.
        let v = vars2();
        let ord = MonomialOrder::Lex;
        let f1 = parse("x^2 + y^2 - 1", &v, ord);
        let f2 = parse("x - y^2", &v, ord);
        let g = buchberger(&[f1, f2]);
        // Two elements, both leading-coeff 1. The last element is purely in y.
        assert_eq!(g.len(), 2);
        let last = &g[g.len() - 1];
        // The pure-y element: lm has zero in x slot.
        assert_eq!(last.lm().unwrap().0[0], 0);
        // Sanity: every original generator reduces to zero mod the basis.
        for f in [parse("x^2 + y^2 - 1", &v, ord), parse("x - y^2", &v, ord)] {
            assert!(normal_form(&f, &g).is_zero());
        }
    }

    #[test] fn groebner_of_already_reduced_basis_is_itself() {
        // Single polynomial input → its (leading-coefficient-1) version is
        // the entire reduced basis.
        let v = vars2();
        let ord = MonomialOrder::Grlex;
        let f = parse("3*x*y + 6*y^2 - 9", &v, ord);
        let g = buchberger(&[f]);
        assert_eq!(g.len(), 1);
        // Leading coefficient normalised to 1.
        assert!(g[0].lc().unwrap().is_one());
    }

    #[test] fn groebner_contains_every_input() {
        // For any Gröbner basis G of (f_1, ..., f_n), each f_i must reduce
        // to zero modulo G.
        let v = vars2();
        let ord = MonomialOrder::Grevlex;
        let inputs = [
            parse("x^2 + y^2 - 4", &v, ord),
            parse("x*y - 1", &v, ord),
        ];
        let g = buchberger(&inputs);
        for f in &inputs {
            let r = normal_form(f, &g);
            assert!(r.is_zero(), "{:?} did not reduce to 0", f.terms);
        }
    }

    #[test] fn groebner_of_inconsistent_system_is_one() {
        // {x, x - 1}: 1 is in the ideal → reduced basis = [1].
        let v = vars2();
        let ord = MonomialOrder::Grlex;
        let inputs = [parse("x", &v, ord), parse("x - 1", &v, ord)];
        let g = buchberger(&inputs);
        assert_eq!(g.len(), 1);
        // The single element should be the constant 1.
        assert_eq!(g[0].terms.len(), 1);
        assert!(g[0].terms[0].0.is_one()); // monomial is "1"
        assert!(g[0].terms[0].1.is_one()); // coefficient is 1
    }

    #[test] fn buchberger_first_criterion_skip_coprime() {
        // {x, y}: leading monomials are coprime. The reduced basis must be
        // exactly {x, y} (under any of the three orders).
        for ord in [MonomialOrder::Lex, MonomialOrder::Grlex, MonomialOrder::Grevlex] {
            let v = vars2();
            let g = buchberger(&[parse("x", &v, ord), parse("y", &v, ord)]);
            assert_eq!(g.len(), 2, "order {:?}", ord);
        }
    }
}
