#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Integer(i64),
    /// Integer with trailing dot (e.g., `2.`). Always decimal, immune to ibase.
    DotInteger(i64),
    Float(f64),
    Ident(String),
    String(String),
    Plus,
    Minus,
    Star,
    Slash,
    Caret,
    Excl,
    Dot,
    SingleQuote,
    DoubleQuote,
    LParen,
    RParen,
    LBracket,
    RBracket,
    LBrace,
    RBrace,
    Comma,
    Semicolon,
    Dollar,
    Colon,
    ColonEqual,
    ColonColon,
    Equal,
    Hash,
    LessThan,
    GreaterThan,
    LessEqual,
    GreaterEqual,
    Eof,
}
